"""create classrooms classroom_members lessons and contents tables

Revision ID: 3a822ce4713b
Revises: b08287af4815
Create Date: 2026-09-14 14:09:36.404348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a822ce4713b'
down_revision = 'b08287af4815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('classroom_id')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_instructor_id'), ['instructor_id'], unique=False)

    op.create_table('classroom_members',
    sa.Column('classroom_member_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classroom_member_id'),
    sa.UniqueConstraint('classroom_id', 'user_id', name='uq_classroom_member')
    )
    with op.batch_alter_table('classroom_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_members_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_user_id'), ['user_id'], unique=False)

    op.create_table('lessons',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_classroom_id'), ['classroom_id'], unique=False)

    op.create_table('contents',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('content_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_lesson_id'), ['lesson_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_lesson_id'))

    op.drop_table('contents')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_classroom_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('classroom_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_members_classroom_id'))

    op.drop_table('classroom_members')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_instructor_id'))

    op.drop_table('classrooms')
    # ### end Alembic commands ###
